testCases:
    - scenarioId: "A1"
      parallelism: -1
    - scenarioId: "A2"
      parallelism: -1
    - scenarioId: "A3"
      parallelism: -1
    - scenarioId: "A4"
      parallelism: -1
    - scenarioId: "A5"
      parallelism: -1
    - scenarioId: "A6"
      parallelism: -1
    - scenarioId: "A7"
      parallelism: -1
    - scenarioId: "A8"
      parallelism: -1
    - scenarioId: "A9"
      parallelism: -1
    - scenarioId: "F1"
      parallelism: -1
    - scenarioId: "F2"
      parallelism: -1
    - scenarioId: "F3"
      parallelism: -1
    - scenarioId: "F4"
      parallelism: -1
    - scenarioId: "F5"
      parallelism: -1
    - scenarioId: "F6"
      parallelism: -1
    - scenarioId: "F7"
      parallelism: -1
    - scenarioId: "F8"
      parallelism: -1
    - scenarioId: "T1"
      parallelism: -1
    - scenarioId: "T2"
      parallelism: -1
    - scenarioId: "T3"
      parallelism: -1
    - scenarioId: "T4"
      parallelism: -1
    - scenarioId: "T5"
      parallelism: -1
    - scenarioId: "T6"
      parallelism: -1
    - scenarioId: "T7"
      parallelism: -1
    - scenarioId: "T8"
      parallelism: -1
    - scenarioId: "T9"
      parallelism: -1